144, Филимонов, 5.1
IgorFilimonov/spbu_2020_c_homeworks pull request #13
Opened 2020-11-06 20:34 UTC by IgorFilimonov

2020-11-07 11:16 UTC, SokolovYaroslav requested changes
Скажи, в чём твой секрет?
Как ты с первого раза всё правильно сделал?

2020-11-07 11:30 UTC, IgorFilimonov commented
@SokolovYaroslav Это плохо, раз вопрос помечен как предложенное изменение?)

2020-11-08 11:08 UTC, SokolovYaroslav commented
Ну нет, не плохо, просто надо на вопрос ответить и получить аппрув :)

2020-11-08 14:57 UTC, IgorFilimonov commented
@SokolovYaroslav Не знаю, как так получилось, возможно из-за того, что растянул задачу на несколько дней, и было больше времени подумать, как и что лучше сделать

2020-11-08 16:50 UTC, SokolovYaroslav requested changes

2020-11-08 16:50 UTC, SokolovYaroslav commented on library/bst.c
> +    if (node->value < value)
Почему в этих трёх ифах такой порядок аргументов в условии?

2020-11-20 12:13 UTC, SokolovYaroslav approved these changes

2020-11-20 12:13 UTC, merged