144, Филимонов, 7.2
IgorFilimonov/spbu_2020_c_homeworks pull request #17
Opened 2020-11-18 15:22 UTC by IgorFilimonov

2020-11-24 11:20 UTC, SpirinEgor requested changes

2020-11-24 11:20 UTC, SpirinEgor commented on homework7/task2.c
> +void readInputData(FILE* inputFile, int* countCities, int* countRoads, Edge*** roads, int* countStates, int*** citiesOfStates)
Воу, 3 в ряд.
Зачем тебе такой ужасный поинтер? Даже 2.

Если это матрица смежности, то её надо спрятать в граф, а здесь просто использовать addEdge

2020-11-27 13:44 UTC, SpirinEgor requested changes
Не смог запустить решение. Файла с примером ввода нет, попробовал 2-3 своих варианта, на них упало

2020-11-28 13:24 UTC, IgorFilimonov commented
[input.txt](https://github.com/IgorFilimonov/spbu_2020_c_homeworks/files/5610646/input.txt)

2020-12-02 13:24 UTC, SpirinEgor approved these changes

2020-12-02 13:26 UTC, SpirinEgor commented
Что-то не очевидно, как мердж конлфикт разрешить, давай сам

2020-12-21 12:29 UTC, merged