144, Филимонов, 9.1
IgorFilimonov/spbu_2020_c_homeworks pull request #25
Opened 2020-12-20 06:47 UTC by IgorFilimonov

2020-12-20 06:56 UTC, IgorFilimonov commented
Можно сделать на доп. баллы после мягкого дедлайна?

2020-12-20 09:27 UTC, SokolovYaroslav commented
Да, давай

2020-12-22 17:06 UTC, SokolovYaroslav requested changes

2020-12-22 17:06 UTC, SokolovYaroslav commented on library/parser/parser.c
> +}
А как тут обошлось без `*` и `/`?

2020-12-22 17:06 UTC, SokolovYaroslav commented on library/parser/parser.c
> +bool isOperation(char* string);
Вынеси все объявление тогда уж наверх

2020-12-22 17:06 UTC, SokolovYaroslav commented on library/parser/parser.c
> +bool E(Token** tokens, int size, int* current);
Хм, у тебя нетерминалы в голове встречаются по одному разу чтоль?

2020-12-22 17:06 UTC, SokolovYaroslav commented
Пока что мало чего понял, вызываю пояснительную бригаду

2020-12-25 10:34 UTC, IgorFilimonov commented on library/parser/parser.c
> +}
Получается так, что dfa разбирает только числа, а знаки операций определяются через isOperation

2020-12-26 19:16 UTC, SokolovYaroslav requested changes
Enter expression:
2 * * 3
This expression is valid

2020-12-26 19:20 UTC, SokolovYaroslav commented on library/parser/parser.c
> +            *current++;
Есть подозрение, что `*current++` и `(*current)++` -- не одно и то же

2020-12-26 19:21 UTC, SokolovYaroslav commented on library/parser/parser.c
> +            *current++;
(О чем кстати говорит CLion)

2020-12-26 19:24 UTC, SokolovYaroslav commented
btw, если нормально инкапсулировать NonTerminal, то логика станет гораздо проще и ошибитья будет сложнее

2020-12-28 21:49 UTC, SokolovYaroslav approved these changes

2020-12-28 21:49 UTC, merged