144, Филимонов, 2.3
IgorFilimonov/spbu_2020_c_homeworks pull request #3
Opened 2020-09-30 13:46 UTC by IgorFilimonov

2020-10-12 07:16 UTC, nbirillo commented
Я так понимаю смотреть еще не нужно?

2020-10-12 08:01 UTC, IgorFilimonov commented
@nbirillo Сейчас проверка стайлгайда работает

2020-10-13 16:38 UTC, nbirillo commented
Ты не поправил все предыдущие комментарии от Егора, например про декомпозицию main, я не буду смотреть, пока ты поправишь все комментарии

2020-10-14 07:59 UTC, IgorFilimonov commented
@nbirillo Я правильно понимаю, что декомпозировать функцию означает разбить ее на логические составляющие? Просто здесь все решение - один маленький цикл

2020-10-14 10:36 UTC, SpirinEgor commented
Решение -- один цикл. Но помимо этого надо ещё считать данные и вывести их. Сейчас за всё это отвечает одна функция, что не есть хорошо.

2020-10-14 16:32 UTC, nbirillo requested changes

2020-10-14 16:32 UTC, nbirillo commented on homework2/task3.c
> +int main()
![image](https://user-images.githubusercontent.com/8993915/96018414-e6ab6a00-0e53-11eb-9cb1-2fecdc627bc3.png)

2020-10-14 17:19 UTC, nbirillo approved these changes
Зачтено!

2020-10-14 17:19 UTC, merged