144, Филимонов, 2.4
IgorFilimonov/spbu_2020_c_homeworks pull request #4
Opened 2020-09-30 14:57 UTC by IgorFilimonov

2020-10-13 16:59 UTC, nbirillo requested changes

2020-10-13 16:59 UTC, nbirillo commented on homework2/task4.c
> +int main()
Хочется, чтобы с числами побольше тоже работало
![image](https://user-images.githubusercontent.com/8993915/95890006-e0ea5180-0d8b-11eb-9456-403d59744a0c.png)

2020-10-13 16:59 UTC, nbirillo commented on homework2/task4.c
> +    }
А зачем так велосипедить то? иди, сразу заполняй массив и увеличивай `numberOfDigits`

2020-10-13 16:59 UTC, nbirillo commented on homework2/task4.c
> +    }
А можно и в функцию вынести

2020-10-14 07:50 UTC, IgorFilimonov commented
Я правильно понимаю, что декомпозировать функцию означает разбить ее на логические составляющие?

2020-10-14 16:34 UTC, nbirillo approved these changes
Зачтено!

2020-10-14 16:34 UTC, merged